"""PyPiTUI components for Alfred CLI."""

# ANSI colors (comprehensive set)
from alfred.interfaces.ansi import (
    BLACK,
    BLUE,
    BOLD,
    BRIGHT_BLACK,
    BRIGHT_BLUE,
    BRIGHT_CYAN,
    BRIGHT_GREEN,
    BRIGHT_MAGENTA,
    BRIGHT_RED,
    BRIGHT_WHITE,
    BRIGHT_YELLOW,
    CYAN,
    DIM,
    GREEN,
    MAGENTA,
    ON_BLACK,
    ON_BLUE,
    ON_BRIGHT_BLACK,
    ON_BRIGHT_BLUE,
    ON_BRIGHT_CYAN,
    ON_BRIGHT_GREEN,
    ON_BRIGHT_MAGENTA,
    ON_BRIGHT_RED,
    ON_BRIGHT_WHITE,
    ON_BRIGHT_YELLOW,
    ON_CYAN,
    ON_GREEN,
    ON_MAGENTA,
    ON_RED,
    ON_WHITE,
    ON_YELLOW,
    RED,
    RESET,
    YELLOW,
)
from alfred.interfaces.pypitui.commands import (
    Command,
    HealthCommand,
    ListSessionsCommand,
    NewSessionCommand,
    ResumeSessionCommand,
    ShowContextCommand,
    ShowSessionCommand,
    ThrobbersCommand,
)
from alfred.interfaces.pypitui.compat import (
    CompatTUI,
    OverlayHandle,
    OverlayOptions,
    ProcessTerminal,
)
from alfred.interfaces.pypitui.constants import (
    DIM_BLUE,
    DIM_GREEN,
    DIM_RED,
)
from alfred.interfaces.pypitui.history_cache import HistoryManager
from alfred.interfaces.pypitui.models import ToolCallInfo
from alfred.interfaces.pypitui.toast import ToastHandler, ToastManager, add_toast
from alfred.interfaces.pypitui.utils import format_tokens

__all__ = [
    # TUI Compatibility
    "CompatTUI",
    "ProcessTerminal",
    "OverlayHandle",
    "OverlayOptions",
    # Commands
    "Command",
    "HealthCommand",
    "ListSessionsCommand",
    "NewSessionCommand",
    "ResumeSessionCommand",
    "ShowContextCommand",
    "ShowSessionCommand",
    "ThrobbersCommand",
    # Components
    "HistoryManager",
    "ToastManager",
    "ToastHandler",
    "ToolCallInfo",
    # Functions
    "add_toast",
    "format_tokens",
    # ANSI Colors
    "BLACK",
    "BLUE",
    "BOLD",
    "BRIGHT_BLACK",
    "BRIGHT_BLUE",
    "BRIGHT_CYAN",
    "BRIGHT_GREEN",
    "BRIGHT_MAGENTA",
    "BRIGHT_RED",
    "BRIGHT_WHITE",
    "BRIGHT_YELLOW",
    "CYAN",
    "DIM",
    "GREEN",
    "MAGENTA",
    "ON_BLACK",
    "ON_BLUE",
    "ON_BRIGHT_BLACK",
    "ON_BRIGHT_BLUE",
    "ON_BRIGHT_CYAN",
    "ON_BRIGHT_GREEN",
    "ON_BRIGHT_MAGENTA",
    "ON_BRIGHT_RED",
    "ON_BRIGHT_WHITE",
    "ON_BRIGHT_YELLOW",
    "ON_CYAN",
    "ON_GREEN",
    "ON_MAGENTA",
    "ON_RED",
    "ON_WHITE",
    "ON_YELLOW",
    "RED",
    "RESET",
    "YELLOW",
    # Dim border colors
    "DIM_BLUE",
    "DIM_GREEN",
    "DIM_RED",
]
