# Alfred shell completions for fish
# Generated automatically - do not edit manually

# Disable file completions by default
complete -c alfred -f

# Top-level options
complete -c alfred -s t -l telegram -d "Run as Telegram bot"
complete -c alfred -s l -l log -d "Set log level" -a "info debug"
complete -c alfred -l install-completions -d "Install shell completions"
complete -c alfred -l help -d "Show help"
complete -c alfred -n "__fish_use_subcommand" -a "daemon"
complete -c alfred -n "__fish_use_subcommand" -a "daemon-stop"
complete -c alfred -n "__fish_use_subcommand" -a "daemon-status"
complete -c alfred -n "__fish_use_subcommand" -a "daemon-reload"
complete -c alfred -n "__fish_use_subcommand" -a "jobs"
complete -c alfred -n "__fish_use_subcommand" -a "cron"
complete -c alfred -n "__fish_use_subcommand" -a "memory"
complete -c alfred -n "__fish_use_subcommand" -a "--telegram"
complete -c alfred -n "__fish_use_subcommand" -a "-t"
complete -c alfred -n "__fish_use_subcommand" -a "--log"
complete -c alfred -n "__fish_use_subcommand" -a "-l"
complete -c alfred -n "__fish_use_subcommand" -a "--install-completions"
complete -c alfred -n "__fish_use_subcommand" -a "--help"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "list"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "submit"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "review"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "approve"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "reject"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "history"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "start"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "stop"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "status"
complete -c alfred -n "__fish_seen_subcommand_from cron" -a "reload"
complete -c alfred -n "__fish_seen_subcommand_from jobs" -a "list"
complete -c alfred -n "__fish_seen_subcommand_from jobs" -a "submit"
complete -c alfred -n "__fish_seen_subcommand_from jobs" -a "review"
complete -c alfred -n "__fish_seen_subcommand_from jobs" -a "approve"
complete -c alfred -n "__fish_seen_subcommand_from jobs" -a "reject"
complete -c alfred -n "__fish_seen_subcommand_from jobs" -a "history"
complete -c alfred -n "__fish_seen_subcommand_from memory" -a "migrate"
complete -c alfred -n "__fish_seen_subcommand_from memory" -a "status"
complete -c alfred -n "__fish_seen_subcommand_from memory" -a "prune"
