"""Tool for saving memories to the unified memory store."""

from collections.abc import AsyncIterator
from datetime import datetime

from pydantic import BaseModel, Field

from src.memory import MemoryEntry
from src.memory.base import MemoryStore
from src.type_defs import JsonValue

from .base import Tool


class RememberToolParams(BaseModel):
    """Parameters for RememberTool."""

    content: str = Field(..., description="The distilled insight or fact to remember")
    tags: str = Field("", description="Comma-separated list of category tags")
    permanent: bool = Field(False, description="Mark as permanent (skip 90-day TTL)")

    class Config:
        extra = "forbid"


class RememberTool(Tool):
    """Save a memory to the unified memory store.

    Use this when the user asks you to remember something,
    or when you learn important facts, preferences, or context
    that would be useful to recall in future conversations.
    """

    name = "remember"
    description = "Save a memory to the unified memory store for future retrieval"
    param_model = RememberToolParams

    def __init__(self, memory_store: MemoryStore | None = None) -> None:
        super().__init__()
        self._memory_store = memory_store

    def set_memory_store(self, memory_store: MemoryStore) -> None:
        """Set the memory store after initialization."""
        self._memory_store = memory_store

    async def execute_stream(self, **kwargs: JsonValue) -> AsyncIterator[str]:
        """Save a memory to the unified store (async).

        Args:
            **kwargs: Tool parameters including:
                - content: The distilled insight or fact to remember
                - tags: Comma-separated list of category tags
                - permanent: Mark as permanent (skip 90-day TTL)

        Yields:
            Confirmation that the memory was saved
        """
        content_value = kwargs.get("content")
        tags_value = kwargs.get("tags", "")
        permanent_value = kwargs.get("permanent", False)

        if not isinstance(content_value, str):
            yield "Error: content must be a string"
            return
        if not isinstance(tags_value, str):
            yield "Error: tags must be a string"
            return
        if not isinstance(permanent_value, bool):
            yield "Error: permanent must be a boolean"
            return

        content = content_value
        tags = tags_value
        permanent = permanent_value

        if not self._memory_store:
            yield "Error: Memory store not initialized"
            return

        # Parse tags
        tag_list = [t.strip() for t in tags.split(",") if t.strip()]

        # Create memory entry
        entry = MemoryEntry(
            timestamp=datetime.now(),
            role="system",  # These are distilled insights, not raw conversation
            content=content,
            embedding=None,  # Will be generated by MemoryStore
            tags=tag_list,
            permanent=permanent,
        )

        try:
            await self._memory_store.add(entry)
            tag_str = f" (tags: {', '.join(tag_list)})" if tag_list else ""
            perm_str = " [permanent]" if permanent else ""
            truncated = content[:100]
            suffix = "..." if len(content) > 100 else ""
            result = f"Remembered: {truncated}{suffix}{tag_str}{perm_str}"
            yield result
        except Exception as e:
            yield f"Error saving memory: {e}"
