"""Tool for saving memories to the unified memory store."""

from collections.abc import AsyncIterator
from datetime import datetime

from src.types import MemoryEntry

from .base import Tool


class RememberTool(Tool):
    """Save a memory to the unified memory store.
    
    Use this when the user asks you to remember something,
    or when you learn important facts, preferences, or context
    that would be useful to recall in future conversations.
    """
    
    name = "remember"
    description = "Save a memory to the unified memory store for future retrieval"
    
    def __init__(self, memory_store=None):
        super().__init__()
        self._memory_store = memory_store
    
    def set_memory_store(self, memory_store):
        """Set the memory store after initialization."""
        self._memory_store = memory_store
    
    def execute(
        self,
        content: str,
        importance: float = 0.5,
        tags: str = "",
    ) -> str:
        """Save a memory to the unified store (sync wrapper - use execute_stream).
        
        Args:
            content: The distilled insight or fact to remember. Be specific and concise.
            importance: How important this memory is (0.0 to 1.0). Use higher values for
                       core preferences, key facts, or things mentioned multiple times.
            tags: Comma-separated list of category tags (e.g., "preferences,coding,work")
        
        Returns:
            Confirmation that the memory was saved
        """
        # This method should not be called directly - use execute_stream
        return "Error: RememberTool must be called via execute_stream in async context"
    
    async def execute_stream(
        self,
        content: str,
        importance: float = 0.5,
        tags: str = "",
    ) -> AsyncIterator[str]:
        """Save a memory to the unified store (async).
        
        Args:
            content: The distilled insight or fact to remember. Be specific and concise.
            importance: How important this memory is (0.0 to 1.0). Use higher values for
                       core preferences, key facts, or things mentioned multiple times.
            tags: Comma-separated list of category tags (e.g., "preferences,coding,work")
        
        Yields:
            Confirmation that the memory was saved
        """
        if not self._memory_store:
            yield "Error: Memory store not initialized"
            return
        
        # Parse tags
        tag_list = [t.strip() for t in tags.split(",") if t.strip()]
        
        # Create memory entry
        entry = MemoryEntry(
            timestamp=datetime.now(),
            role="system",  # These are distilled insights, not raw conversation
            content=content,
            embedding=None,  # Will be generated by MemoryStore
            importance=importance,
            tags=tag_list,
        )
        
        try:
            await self._memory_store.add_entries([entry])
            tag_str = f" (tags: {', '.join(tag_list)})" if tag_list else ""
            result = f"Remembered: {content[:100]}{'...' if len(content) > 100 else ''}{tag_str}"
            yield result
        except Exception as e:
            yield f"Error saving memory: {e}"
